/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi2023.mavenproject1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.xml.parsers.ParserConfigurationException;
import org.json.simple.parser.ParseException;
import org.xml.sax.SAXException;

/**
 *
 * @author Kseny
 */
public class VisualReactorJFrame extends javax.swing.JFrame {
    private final DataManipulation dataManipulation;
    /**
     * Creates new form VisualReactorJFrame
     */
    public VisualReactorJFrame() {
        super("Сводка о реакторах");
        initComponents();
        setSize(600, 400);
        reactorTypeFileChooser.setVisible(false);
        dataManipulation = new DataManipulation();
        fileLabel.setText("файл не выбран");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reactorTypeFileChooser = new javax.swing.JFileChooser();
        mainLabel = new javax.swing.JLabel();
        chooseFileButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reactorTree = new javax.swing.JTree();
        fileLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        reactorTypeFileChooser.setApproveButtonMnemonic(1);
        reactorTypeFileChooser.setApproveButtonText("");
        reactorTypeFileChooser.setApproveButtonToolTipText("");
        reactorTypeFileChooser.setCurrentDirectory(new java.io.File("D:\\Users\\Kseny\\OneDrive\\Документы\\NetBeansProjects\\mavenproject1\\src\\main\\resources"));
        reactorTypeFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reactorTypeFileChooserActionPerformed(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Данные о реакторах:");

        chooseFileButton.setText("выбрать файл");
        chooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileButtonActionPerformed(evt);
            }
        });

        drawButton.setText("выгрузить данные");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Реакторы");
        reactorTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(reactorTree);

        fileLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        fileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(reactorTypeFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(drawButton)
                        .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chooseFileButton))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(reactorTypeFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reactorTypeFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reactorTypeFileChooserActionPerformed
        System.out.println(evt);
        if (reactorTypeFileChooser.getSelectedFile() != null){
            System.out.println(reactorTypeFileChooser.getSelectedFile());
            String fileName = reactorTypeFileChooser.getSelectedFile().getAbsolutePath();
            dataManipulation.clearCollections();
            if(fileName.endsWith("json")){
                try {
                    dataManipulation.readFromJSON(fileName);
                    fileLabel.setText("json");
                } catch (IOException | ParseException ex) {
                    Logger.getLogger(VisualReactorJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(fileName.endsWith("yml")){
                try {
                    dataManipulation.readFromYAML(fileName);
                    fileLabel.setText("yaml");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(VisualReactorJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(fileName.endsWith("xml")){
                try {
                    dataManipulation.readFromXML(fileName);
                    fileLabel.setText("xml");
                } catch (SAXException | IOException | ParserConfigurationException ex) {
                    Logger.getLogger(VisualReactorJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
        } else{
            System.out.println(":(");
            
        }
        reactorTypeFileChooser.setSelectedFile(new File(""));
    }//GEN-LAST:event_reactorTypeFileChooserActionPerformed

    private void chooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileButtonActionPerformed
        String homeDir = System.getProperty("user.dir")+"\\src\\main\\resources\\";
        System.out.println(homeDir +"\\src\\main\\resources\\");
        reactorTypeFileChooser.setCurrentDirectory(new File(homeDir));
        reactorTypeFileChooser.setVisible(true);
        reactorTypeFileChooser.setSize(600, 400);
        reactorTypeFileChooser.showDialog(null, "Open");
        
    }//GEN-LAST:event_chooseFileButtonActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode main = dataManipulation.addInfoToTree();
        reactorTree.setModel(new DefaultTreeModel(main));
    }//GEN-LAST:event_drawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFileButton;
    private javax.swing.JButton drawButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTree reactorTree;
    private javax.swing.JFileChooser reactorTypeFileChooser;
    // End of variables declaration//GEN-END:variables
}
